name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v3

      - name: Set up Ruby for Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # You can change this to the Ruby version you're using

      - name: Install dependencies (Ruby & npm)
        run: |
          gem install bundler
          bundle install
          npm install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages Repo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site  # Adjust this if your build folder is different
          repository-name: Prod-CXXL/HEXA1A5A9-Public
          token: ${{ secrets.GH_PAT }}
