name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main # Change this to your master branch's name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2 # Adjust as needed

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install
          npm install
      
      - name: Build Jekyll Site
        run: |
          bundle exec jekyll build
     
      - name: Deploy Site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          external_repository: Prod-CXXL/HEXA1A5A9-Public
          deploy_key: ${{ secrets.GH_PAT }}
          publish_branch: main # Change this to your master branch's name
          publish_dir: ./_site # change to the output dir of your Jekyll build
